version: "3"
services:
  nginx-proxy:
    image: lennonalvesdias/proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
  default:
    external:
      name: nginx-proxy